export const TEXTS = {
  appTitle: "Flight Trip Planner",
  common: {
    userFallback: "User",
    unknown: "Unknown",
  },
  buttons: {
    signIn: "Sign In",
    signOut: "Sign Out",
    register: "Register",
    openControls: "Settings",
    closeControls: "✕ Close settings",
    search: "Search",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    save: "Save",
    edit: "Edit",
    clear: "Clear",
    tryAgain: "Try again",
    refresh: "Refresh",
    load: "Load",
    rename: "Rename",
    undo: "Undo",
    redo: "Redo",
    close: "Close"
  },
  auth: {
    updateTripTitle: "Update existing trip",
    saveTripTitle: "Save current trip",
    createAccount: "Create Account",
    email: "Email",
    password: "Password",
    pleaseWait: "Please wait...",
    register: "Register",
    checkEmail: "Check your email to confirm your account.",
    continueGoogle: "Continue with Google",
    noAccount: "No account?",
    haveAccount: "Have an account?",
    saveTrip: "Save Trip",
    updateTrip: "Update Trip",
    saving: "Saving...",
    nameYourTrip: "Name your trip",
    autoNamePrefix: "Trip ",
  },
  map: {
    searchPlaceholder: "Search locations...",
  },
  flights: {
    never: 'Never',
    justNow: 'Just now',
    minutesAgo: (minutes: number) => `${minutes} min ago`,
    hoursAgo: (hours: number) => `${hours}h ago`,
    loadingFrom: (code: string) => `Loading flights from ${code}...`,
    noFlightsMatchFilters: "No flights match the current filters",
    noFlightsForDate: (date: string) => `No flights for ${date}`,
    tryAdjustFilters: "Try adjusting or clearing filters",
    tryDifferentDate: "Try selecting a different date",
    lastUpdated: "Last updated: "
  },
  date: {
    placeholder: "DD/MM/YYYY"
  },
  search: {
    expandToShowCities: "Expand to show cities",
    countries: "Countries",
    cities: "Cities",
    airports: "Airports",
    containsSearch: " (Contains Search)",
    loaded: " (Loaded)",
    placeholder: "Search countries, cities, airports...",
    error: "Search Component Error",
    loading: "Loading...",
    loadingDetails: "Loading details...",
    noCities: "No cities",
    noCitiesAvailable: "No cities available",
    scrollMore: "Scroll for more",
    expandToShowAirports: "Expand to show airports",
    collapse: "Collapse",
    noAirportsForCity: (city: string) => `No airports available for ${city}`,
    loadingAirportsForCity: (city: string) => `Loading airports for ${city}...`,
    clickExpandCities: (country: string) => `Click expand to load cities for ${country}`,
    loadingCitiesForCountry: (country: string) => `Loading cities for ${country}...`,
    airportCode: "Airport code",
    noResultsFound: (query: string) => `No results found for "${query}"`,
    searchResults: "Search Results",

    scrolling: (count: number) => ` (Scrolling ${count} countries...)`,
    debugPhase1: (count: number) => `Phase 1: Showing ${count} matching countries (collapsed by default)`,
    expand: "Expand"
  },
  filter: {
    title: "Filters",
    countries: "Countries",
    cities: "Cities",
    airports: "Airports",
    searchDestinations: "Search destinations..."
  },
  transferPicker: {
    toSearch: "to search",
    clickToAdd: "Click to add airports to search",
    searchAirports: "Search airports to add...",
    noAirports: "No airports found",
    addAirports: (count: number) => `Add ${count} airport${count !== 1 ? 's' : ''}`
  },
  panel: {
    selectedCount: (selected: number, max: number) => `${selected}/${max} airports selected`,

    originalAirport: "Original airport",
    transferAirports: "Transfer airports",
    switchTimezone: "Click to switch timezone",
    destinations: "Destinations",
    airlines: "Airlines",
    departureDate: "Departure date",
    loadingAirports: "Loading airports...",
    noFlightableAirports: "No flightable airports",
    noFlightableAirportsCity: "No flightable airports found for this city.",
    loadingCities: "Loading cities...",
    selectAirportsAbove: "Select airports above to view departing flights.",
    loadingFlights: "Loading flights...",
    departingFlights: "Departing Flights",
    selectAirportsMax: (max: number) => `Select airports (max ${max})`,
    loadFlightsFromCount: (count: number) => `Load flights from ${count} airport(s)`,
    selectCitiesMax: (max: number) => `Select cities (max ${max} airports total)`,
    addAirportsFrom: "Add airports from ",
    addCountAirports: (count: number) => `Add ${count} airport${count !== 1 ? 's' : ''}`,
    airportAbbreviation: "ap"
  },
  card: {
    terminal: "Terminal:",
    gate: "Gate:",
    flightTime: "Flight time:",
    estArrival: "Est. arrival:",
    departure: "Departure",
    arrival: "Arrival",
    searchOnline: "Search online",
    loadingPrices: "Loading prices...",
    failedPrices: "Failed to load prices",
    noPrices: "No prices available for this flight",
    bookTicket: "Book ticket",
    addTrip: "Add to trip",
    showPrices: "Show prices",
    hidePrices: "Hide prices",
    noFlightsForDate: "No flights for selected date",
    clickRouteToFilter: "Click route to filter by destination",
    estimated: "~ estimated",
    estimatedTooltip: "Estimated arrival — calculated from flight distance and average aircraft speed (~850 km/h)",
    origin: "Origin",
    destination: "Destination",
    loading: "Loading...",
    oneWay: " one way",
    na: "N/A"
  },
  days: {
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun"
  },
  trip: {
    tripEnded: "Trip has already ended",
    editTrip: "Edit this trip",
    timeInCity: (city: string) => `Time in ${city}`,
    transfer: "Transfer: ",
  },
  savedTrips: {
    title: "Saved trips",
    loading: "Loading...",
    failed: "Failed to load trips",
    noTrips: "No saved trips",
    tripId: (id: string | number) => `Trip #${id}`,
    country: "country",
    countries: "countries",
    rename: "Rename",
    delete: "Delete",
    load: "Load",
    nameYourTrip: "Name your trip",
    save: "Save"
  },
  modals: {
    thisTrip: "this trip",
    undoWarning: "This action cannot be undone.",
    namePlaceholder: "Leave empty for auto-generated name",
    deleteTrip: "Delete trip?",
    sureDelete: "Are you sure you want to delete",

  },
  controls: {
    failedRoutes: "Failed to load routes",
    darkMatter: "Dark Matter",
    positron: "Positron",
    voyager: "Voyager",
    satellite: "Satellite",
    imagery: "ArcGIS Imagery",
    charted: "ArcGIS Charted Territory",
    community: "ArcGIS Community",
    globe: "Globe",
    showRefresh: "Show Refresh Button",
    showConsole: "Show Console Logs",
    loadRoutes: "Load Routes",
    customizeStyles: "Customize Styles",
    hideStyles: "Hide Styles",
    developer: "Developer",
    hideDeveloper: "Hide Developer",
    mapSizeSettings: "Map Size Settings",
    hideSizeSettings: "Hide Size Settings",
    resetAll: "Reset all",
    resetSizes: "Reset sizes",
    zoom: "Zoom:",
    eyedropper: "Eyedropper",
    pickColor: "Pick color from screen",
    notSupportedBrowser: "Not supported in this browser",
    currency: "Currency:",
    minTransferTime: "Min. transfer time:",
    minManualTransfer: "Min. manual transfer:",
    mapStyle: "Map Style:",
    lightDefault: "Light (default)",
    airportsCount: "Airports: ",
    routesCount: "Routes: ",
    loading: "(loading...)",
    switchToFlat: "Switch to flat map",
    switchToGlobe: "Switch to globe"
  },
  colorSettings: {
    picker: {
      selectWindow: "Select window in browser dialog…",
      clickToPick: "Click to pick · Esc to cancel"
    },
    colors: "Colors",
    generalAirports: "General airports",
    destinationAirports: "Destination airports",
    tripAirports: "Trip airports",
    sameAirport: "Same airport",
    sameCity: "Same city",
    sameCountry: "Same country",
    departsTooSoon: "Departs too soon",
    tripRoute: "Trip route",
    transferRoute: "Transfer route",
    transferPreview: "Transfer preview",
    routeLineWidth: "Route line width",
    routeLineHoverWidth: "Route line hover width",
    tripRouteWidth: "Trip route line width",
    tripRouteHoverWidth: "Trip route line hover width",
    generalDotSize: "General dot size",
    generalDotHoverSize: "General dot hover size",
    highlightedDotSize: "Highlighted dot size",
    highlightedDotHoverSize: "Highlighted dot hover size",
    generalLabelSize: "General label size",
    generalLabelHoverSize: "General label hover size",
    highlightedLabelSize: "Highlighted label size",
    highlightedLabelHoverSize: "Highlighted label hover size",
    startingPoints: "Starting points",
    mapElements: "Map elements",
    airports: "Airports",
    routes: "Routes",
    flightCardHighlights: "Flight card highlights",
    sizes: "Sizes",
    zoomRange: "Zoom range",
    pointLabel: (n: number) => `Point ${n}`,
    help: {
      airportDot: "Airport dot",
      airportDotHover: "Airport dot hover",
      routeLine: "Route line",
      routeLineHover: "Route line hover",
      labelColor: "Label color",
      labelHoverColor: "Label hover color",
      dotColor: "Dot color",
      dotHoverColor: "Dot hover color",
      color: "Color",
      hoverColor: "Hover color",
      bgColor: "Background color",
      borderColor: "Border color"
    }
  },
  errors: {
    generic: "Something went wrong.",
    mapNotLoaded: "Map could not be loaded",
    webglNotSupported: "WebGL is not supported in your browser. Please update or try a different browser.",
    noResults: "No results found"
  }
};
