import { useColorStore } from '../../stores/colorStore';

export function useMapColors() {

  return {
    startPoints: useColorStore(s => s.startPoints),
    generalAirport: useColorStore(s => s.generalAirport),
    destinationAirport: useColorStore(s => s.destinationAirport),
    tripAirport: useColorStore(s => s.tripAirport),
    tripRoute: useColorStore(s => s.tripRoute),
    transferRoute: useColorStore(s => s.transferRoute),
    tripAirportHover: useColorStore(s => s.tripAirportHover),
    generalAirportHover: useColorStore(s => s.generalAirportHover),
    destinationAirportHover: useColorStore(s => s.destinationAirportHover),
    transferRouteHover: useColorStore(s => s.transferRouteHover),
    generalLabelHoverColor: useColorStore(s => s.generalLabelHoverColor),
    generalLabelColor: useColorStore(s => s.generalLabelColor),
    destinationLabelColor: useColorStore(s => s.destinationLabelColor),
    destinationLabelHoverColor: useColorStore(s => s.destinationLabelHoverColor),
    tripLabelColor: useColorStore(s => s.tripLabelColor),
    tripLabelHoverColor: useColorStore(s => s.tripLabelHoverColor),
    routeLineWidthMin: useColorStore(s => s.routeLineWidthMin),
    routeLineWidthMax: useColorStore(s => s.routeLineWidthMax),
    routeLineHoverWidthMin: useColorStore(s => s.routeLineHoverWidthMin),
    routeLineHoverWidthMax: useColorStore(s => s.routeLineHoverWidthMax),
    highlightedAirportRadiusMin: useColorStore(s => s.highlightedAirportRadiusMin),
    highlightedAirportRadiusMax: useColorStore(s => s.highlightedAirportRadiusMax),
    highlightedAirportHoverRadiusMin: useColorStore(s => s.highlightedAirportHoverRadiusMin),
    highlightedAirportHoverRadiusMax: useColorStore(s => s.highlightedAirportHoverRadiusMax),
    generalAirportRadiusMin: useColorStore(s => s.generalAirportRadiusMin),
    generalAirportRadiusMax: useColorStore(s => s.generalAirportRadiusMax),
    generalAirportHoverRadiusMin: useColorStore(s => s.generalAirportHoverRadiusMin),
    generalAirportHoverRadiusMax: useColorStore(s => s.generalAirportHoverRadiusMax),
    tripRouteWidthMin: useColorStore(s => s.tripRouteWidthMin),
    tripRouteWidthMax: useColorStore(s => s.tripRouteWidthMax),
    tripRouteHoverWidthMin: useColorStore(s => s.tripRouteHoverWidthMin),
    tripRouteHoverWidthMax: useColorStore(s => s.tripRouteHoverWidthMax),
    highlightedCity: useColorStore(s => s.highlightedCity),
    generalCity: useColorStore(s => s.generalCity),
    highlightedCityRadius: useColorStore(s => s.highlightedCityRadius),
    generalCityRadius: useColorStore(s => s.generalCityRadius),
    generalAirportLabelSizeMin: useColorStore(s => s.generalAirportLabelSizeMin),
    generalAirportLabelSizeMax: useColorStore(s => s.generalAirportLabelSizeMax),
    generalLabelHoverSizeMin: useColorStore(s => s.generalLabelHoverSizeMin),
    generalLabelHoverSizeMax: useColorStore(s => s.generalLabelHoverSizeMax),
    highlightedLabelSizeMin: useColorStore(s => s.highlightedLabelSizeMin),
    highlightedLabelSizeMax: useColorStore(s => s.highlightedLabelSizeMax),
    highlightedLabelHoverSizeMin: useColorStore(s => s.highlightedLabelHoverSizeMin),
    highlightedLabelHoverSizeMax: useColorStore(s => s.highlightedLabelHoverSizeMax),
    zoomRangeMin: useColorStore(s => s.zoomRangeMin),
    zoomRangeMax: useColorStore(s => s.zoomRangeMax),
  };
}
